// Fetch movies
export const GET_MOVIES_REQUEST = 'GET_MOVIES_REQUEST';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_ERROR = 'GET_MOVIES_ERROR';

export const UPDATE_MOVIES = 'UPDATE_MOVIES';

// Edit page
export const SHOW_EDIT_MOVIE_PAGE = 'SHOW_EDIT_MOVIE_PAGE';
export const HIDE_EDIT_MOVIE_PAGE = 'HIDE_EDIT_MOVIE_PAGE';

// Modals

// ADD movie modal
export const SHOW_MODAL_ADD_MOVIE = 'SHOW_MODAL_ADD_MOVIE';
export const HIDE_MODAL_ADD_MOVIE = 'HIDE_MODAL_ADD_MOVIE';

// Delete movie modal
export const SHOW_MODAL_DELETE_MOVIE = 'SHOW_MODAL_DELETE_MOVIE';
export const HIDE_MODAL_DELETE_MOVIE = 'HIDE_MODAL_DELETE_MOVIE';

// Edit movie modal
export const SHOW_MODAL_EDIT_MOVIE = 'SHOW_MODAL_EDIT_MOVIE';
export const HIDE_MODAL_EDIT_MOVIE = 'HIDE_MODAL_EDIT_MOVIE';

// Forms

export const HANDLE_ADD_MOVIE_FORM_FIELD = 'HANDLE_ADD_MOVIE_FORM_FIELD';
export const HANDLE_GENRE_CHANGE = 'HANDLE_GENRE_CHANGE';
export const CLEAR_EDIT_FORM = 'CLEAR_EDIT_FORM';

export const SET_EDIT_MOVIE_ID = 'SET_EDIT_MOVIE_ID';
export const REMOVE_EDIT_MOVIE_ID = 'REMOVE_EDIT_MOVIE_ID';
export const SET_DELETE_MOVIE_ID = 'SET_DELETE_MOVIE_ID';
export const REMOVE_DELETE_MOVIE_ID = 'REMOVE_DELETE_MOVIE_ID';