// Fetch movies
export const GET_MOVIES_REQUEST = 'GET_MOVIES_REQUEST';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_ERROR = 'GET_MOVIES_ERROR';
export const SUCCESS_UPDATE_MOVIE = 'SUCCESS_UPDATE_MOVIE';
export const SUCCESS_ADDED_MOVIE = 'SUCCESS_ADDED_MOVIE';
export const GET_MOVIE_BY_ID_SUCCESS = 'GET_MOVIE_BY_ID_SUCCESS';

// Modals

// ADD movie modal
export const SHOW_MODAL_ADD_MOVIE = 'SHOW_MODAL_ADD_MOVIE';
export const HIDE_MODAL_ADD_MOVIE = 'HIDE_MODAL_ADD_MOVIE';

// Delete movie modal
export const SHOW_MODAL_DELETE_MOVIE = 'SHOW_MODAL_DELETE_MOVIE';
export const HIDE_MODAL_DELETE_MOVIE = 'HIDE_MODAL_DELETE_MOVIE';

// Edit movie modal
export const SHOW_MODAL_EDIT_MOVIE = 'SHOW_MODAL_EDIT_MOVIE';
export const HIDE_MODAL_EDIT_MOVIE = 'HIDE_MODAL_EDIT_MOVIE';


export const SET_EDIT_MOVIE_ID = 'SET_EDIT_MOVIE_ID';
export const REMOVE_EDIT_MOVIE_ID = 'REMOVE_EDIT_MOVIE_ID';
export const SET_DELETE_MOVIE_ID = 'SET_DELETE_MOVIE_ID';
export const REMOVE_DELETE_MOVIE_ID = 'REMOVE_DELETE_MOVIE_ID';

//Filters
export const SET_ACTIVE_FILTER = 'SET_ACTIVE_FILTER';
export const SORT_BY = 'SORT_BY';